service: image-thumbnail

frameworkVersion: '2 || 3'

custom:
  bucket: test-demo15

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  profile: abc
  iam: 
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource:
            - arn:aws:s3:::${self:custom.bucket}
            - arn:aws:s3:::${self:custom.bucket}/*
  lambdaHashingVersion: 20201221
  environment:
    STAGE: ${env:STAGE}
    PASS_NEW: ${env:PASS_NEW}

useDotenv: true

package: 
  individually: true
  patterns:
    - "!node_modules/**"
    - "!package.json"
    - "!resources"
    - "!.serverless/**"
    - "!.gitignore"
    - "!.env"
    - "!requirements.in"
    - "!requirements.txt"
    - "!venv"
    - "!package-lock.json"
    - "!yarn.lock"
    - "!rough.py"
    - "!.mypy_cache"
  excludeDevDependencies: true

functions:
  - ${file(functions/index.yml)}

plugins:
  - serverless-python-requirements
  - serverless-offline
  